cadastro/urls.py
from django.urls import path

from cadastro.views import FuncionarioCreate, FuncionarioUpdate, PacienteCreate, PacienteUpdate, FuncionarioDelete, PacienteDelete, FuncionarioList, PacienteList

urlpatterns = [
    path('cadastrar/funcionario/', FuncionarioCreate.as_view(), name='cadastro-funcionario'),
    path('cadastrar/paciente/', PacienteCreate.as_view(), name='cadastro-paciente'),

    path('editar/funcionario/<int:pk>/', FuncionarioUpdate.as_view(), name='editar-funcionario'),
    path('editar/paciente/<int:pk>/', PacienteUpdate.as_view(), name='editar-paciente'),

    path('excluir/funcionario/<int:pk>/', FuncionarioDelete.as_view(), name='excluir-funcionario'),
    path('excluir/paciente/<int:pk>/', PacienteDelete.as_view(), name='excluir-paciente'),

    path('listar/funcionarios/', FuncionarioList.as_view(), name='listar-funcionarios'),
    path('listar/pacientes/', PacienteList.as_view(), name='listar-pacientes'),
]

clinica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('paginas/', include('paginas.urls')),
    path('cadastro/', include('cadastro.urls')),
    path('', include('usuarios.urls')),
]

cadastro/models.py
from django.db import models
from django.contrib.auth.models import User

class Base(models.Model):
    criados = models.DateField('Criação', auto_now_add=True)
    modificado = models.DateField('Atualização', auto_now=True)
    ativo = models.BooleanField('Ativo?', default=True)

    class Meta:
        abstract = True

CARGO_CHOICES =(
    ('me', 'Médico(a)'),
    ('ax', 'Auxiliar de limpeza'),
    ('re', 'Recepcionista'),
    ('as', 'Assistente'),
)

ESTADO_CIVIL_CHOICES = (
    ('s', 'Solteiro(a)'),
    ('c', 'Casado(a)'),
    ('d', 'Divorciado(a)'),
    ('v', 'Viúvo(a)'),    
)

SEXO_CHOICES = (
    ('m', 'Masculino'),
    ('f', 'Feminino'),
    ('o', 'Outro'),
)

ESTADOS_CHOICES = (
    ('ac', 'Acre'),
    ('al', 'Alagoas'),
    ('ap', 'Amapá'),
    ('am', 'Amazonas'),
    ('ba', 'Bahia'),
    ('ce', 'Ceará'),
    ('df', 'Distrito Federal'),
    ('es', 'Espírito Santo'),
    ('go', 'Goiás'),
    ('ma', 'Maranhão'),
    ('mt', 'Mato Grosso'),
    ('ms', 'Mato Grosso do Sul'),
    ('mg', 'Minas Gerais'),
    ('pa', 'Pará'),
    ('pb', 'Paraíba'),
    ('pr', 'Paraná'),
    ('pe', 'Pernambuco'),
    ('pi', 'Piauí'),
    ('rj', 'Rio de Janeiro'),
    ('rn', 'Rio Grande do Norte'),
    ('rs', 'Rio Grande do Sul'),
    ('ro', 'Rondônia'),
    ('rr', 'Roraima'),
    ('sc', 'Santa Catarina'),
    ('sp', 'São Paulo'),
    ('se', 'Sergipe'),
    ('to', 'Tocantins'),
)

class Funcionario(Base):
    nome = models.CharField('Nome', max_length=100)
    cargo = models.CharField('Cargo', max_length=2, choices=CARGO_CHOICES)
    cpf = models.CharField('CPF', max_length=14, unique=True)
    rg = models.CharField('RG', max_length=8, unique=True)
    estado_civil = models.CharField('Estado civil', max_length=1, choices=ESTADO_CIVIL_CHOICES)
    nascimento = models.DateField(verbose_name= 'Data de Nasc.')
    sexo = models.CharField('Sexo', max_length=1, choices=SEXO_CHOICES)    
    endereco = models.CharField('Endereço', max_length=100)
    numero = models.CharField('Nº', max_length=10)
    complemento = models.CharField('Complemento', max_length=150, null=True, blank=True)
    bairro = models.CharField('Bairro', max_length=150)
    cep = models.CharField('CEP', max_length=9)
    uf = models.CharField('UF', max_length=2, choices=ESTADOS_CHOICES)
    cidade = models.CharField('Cidade', max_length=150)
    telefone_res = models.CharField('Telefone residencial', max_length=15, null=True, blank=True)
    celular = models.CharField('Celular', max_length=15)
    observacoes = models.TextField('Observações', max_length=300, null=True, blank=True)

    class Meta:
        verbose_name = 'Funcionario'
        verbose_name_plural = 'Funcionarios'

    def __str__(self):
        return self.nome


class Medico(Base):
    medico = models.CharField('Médico', max_length=100)

    class Meta:
        verbose_name = 'Medico'
        verbose_name_plural = 'Medicos'

    def __str__(self):
        return self.medico

class Paciente(Base):    
    paciente = models.CharField('Paciente', max_length=100)
    profissao = models.CharField('Profissão', null=True, blank=True, max_length=50)
    cpf = models.CharField('CPF', max_length=14, unique=True)
    estado_civil = models.CharField('Estado civil', max_length=1, choices=ESTADO_CIVIL_CHOICES)
    nascimento = models.DateField(verbose_name= 'Data de Nascimento')
    sexo = models.CharField('Sexo', max_length=1, choices=SEXO_CHOICES)    
    endereco = models.CharField('Endereço', max_length=100)
    numero = models.CharField('Nº', max_length=10)
    complemento = models.CharField('Complemento', max_length=150, null=True, blank=True)
    bairro = models.CharField('Bairro', max_length=150)
    cep = models.CharField('CEP', max_length=9)
    uf = models.CharField('UF', max_length=2, choices=ESTADOS_CHOICES)
    cidade = models.CharField('Cidade', max_length=150)
    telefone_res = models.CharField('Telefone residencial', max_length=15, null=True, blank=True)
    celular = models.CharField('Celular', max_length=15)
    sus = models.CharField('Número do cartão SUS', max_length=15, unique=True)
    medico = models.ForeignKey('cadastro.Medico', verbose_name='Médico do paciente', on_delete=models.PROTECT)    
    observacoes = models.TextField('Observações', max_length=300, null=True, blank=True)    

    class Meta:
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'

    def __str__(self):
        return self.paciente

cadastro/forms.py
from django.forms import ModelForm
from django import forms
from cadastro.models import Funcionario, Medico, Paciente

class FuncionarioFormAdmin(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(FuncionarioFormAdmin, self).__init__(*args, **kwargs)
        self.fields['cpf'].widget.attrs['class'] = 'mask-cpf'
        self.fields['rg'].widget.attrs['class'] = 'mask-rg'
        self.fields['nascimento'].widget.attrs['class'] = 'mask-nascimento'
        self.fields['numero'].widget.attrs['class'] = 'mask-numero'
        self.fields['cep'].widget.attrs['class'] = 'mask-cep'
        self.fields['telefone_res'].widget.attrs['class'] = 'mask-telefone_res'
        self.fields['celular'].widget.attrs['class'] = 'mask-celular'


class MedicoForm(ModelForm):
    class Meta:
        model = Medico
        fields = '__all__'

class PacienteFormAdmin(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PacienteFormAdmin, self).__init__(*args, **kwargs)
        self.fields['cpf'].widget.attrs['class'] = 'mask-cpf'
        self.fields['nascimento'].widget.attrs['class'] = 'mask-nascimento'
        self.fields['numero'].widget.attrs['class'] = 'mask-numero'
        self.fields['cep'].widget.attrs['class'] = 'mask-cep'
        self.fields['telefone_res'].widget.attrs['class'] = 'mask-telefone_res'
        self.fields['celular'].widget.attrs['class'] = 'mask-celular'
        self.fields['sus'].widget.attrs['class'] = 'mask-sus'

cadastro/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from cadastro.models import Funcionario, Paciente
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import GroupRequiredMixin
from django.shortcuts import get_object_or_404

class FuncionarioCreate(GroupRequiredMixin, LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    group_required = u"Administrador"        
    model = Funcionario
    fields = ['nome', 'cargo', 'cpf', 'rg', 'estado_civil', 'nascimento', 'sexo', 'endereco', 'numero', 'complemento', 'bairro', 'cep', 'uf', 'cidade', 'telefone_res', 'celular', 'observacoes']
    template_name = 'cadastro/form.html'
    success_url = reverse_lazy('listar-funcionarios')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Cadastro do Funcionário"
        context['botao'] = "Cadastrar"

        return context
    

class PacienteCreate(GroupRequiredMixin, LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    group_required = u"Administrador"
    model = Paciente
    fields = ['paciente', 'profissao', 'cpf', 'estado_civil', 'nascimento', 'sexo', 'endereco', 'numero', 'complemento', 'bairro', 'cep', 'uf', 'cidade', 'telefone_res', 'celular', 'sus', 'medico', 'observacoes']
    template_name = 'cadastro/form.html'
    success_url = reverse_lazy('listar-pacientes')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Cadastro do Paciente"
        context['botao'] = "Cadastrar"
        return context


class FuncionarioUpdate(GroupRequiredMixin, LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    group_required = u"Administrador"       
    model = Funcionario
    fields = ['nome', 'cargo', 'cpf', 'rg', 'estado_civil', 'nascimento', 'sexo', 'endereco', 'numero', 'complemento', 'bairro', 'cep', 'uf', 'cidade', 'telefone_res', 'celular', 'observacoes'] 
    template_name = 'cadastro/form.html'  
    success_url = reverse_lazy('listar-funcionarios')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Editar cadastro do Funcionário"
        context['botao'] = "Salvar"

        return context


class PacienteUpdate(GroupRequiredMixin, LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    group_required = u"Administrador"    
    model = Paciente
    fields = ['paciente', 'profissao', 'cpf', 'estado_civil', 'nascimento', 'sexo', 'endereco', 'numero', 'complemento', 'bairro', 'cep', 'uf', 'cidade', 'telefone_res', 'celular', 'sus', 'medico', 'observacoes'] 
    template_name = 'cadastro/form.html'  
    success_url = reverse_lazy('listar-pacientes')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Editar cadastro do Paciente"
        context['botao'] = "Salvar"

        return context


class FuncionarioDelete(GroupRequiredMixin, LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('login')
    group_required = u"Administrador"
    model = Funcionario
    template_name = 'cadastro/form-excluir.html'
    success_url = reverse_lazy('listar-funcionarios')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Excluir Funcionário"        

        return context


class PacienteDelete(GroupRequiredMixin, LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('login')
    group_required = u"Administrador"
    model = Paciente
    template_name = 'cadastro/form-excluir.html'
    success_url = reverse_lazy('listar-pacientes')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Excluir Paciente"        

        return context


class FuncionarioList(GroupRequiredMixin, LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    group_required = [u"Visitante", u"Administrador"]
    model = Funcionario
    template_name = 'cadastro/listas/funcionario.html'
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Lista de Funcionarios Cadastrados" 

        return context

    def get_queryset(self):

        txt_nome = self.request.GET.get('nome')

        if txt_nome:
            funcionarios = Funcionario.objects.filter(nome__icontains=txt_nome)
        else:
            funcionarios = Funcionario.objects.all()
        
        return funcionarios


class PacienteList(GroupRequiredMixin, LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    group_required = [u"Visitante", u"Administrador"]
    model = Paciente
    template_name = 'cadastro/listas/paciente.html'    
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Lista de Pacientes Cadastrados"    

        return context


    def get_queryset(self):

        txt_paciente = self.request.GET.get('paciente')

        if txt_paciente:
            pacientes = Paciente.objects.filter(paciente__icontains=txt_paciente)
        else:
            pacientes = Paciente.objects.all()

        return pacientes

cadastro/templates/cadastro/listas/funcionario.html
{% extends 'paginas/modelo.html' %}
{% load static %}
{% load crispy_forms_tags %}

    {% block conteudo %}        
    <div style="text-align: center;">
        <h3>{{ titulo }}</h3>
    </div>

    <hr>
    <form action="?" method="GET">
        <input type="text" name="nome" id="" value="{{ request.GET.nome }}" class="p-1 border" autocomplete="off" placeholder="Digite o nome do funcionário">  
        
        <button type="submit" class="btn btn-success">Buscar</button>

        <a href="{% url 'listar-funcionarios' %}" class="btn btn-light">Limpar</a>
    </form>

    <hr>

    <a href="{% url 'cadastro-funcionario' %}" class="btn btn-primary btn-sm">Adicionar Funcionário</a>

    <hr>    
        <div class="table-responsive">        
            <table class="table table-striped">
                <tr>                        
                    <th>Nome</th>
                    <th>Cargo</th>
                    <th>CPF</th>
                    <th>RG</th>
                    <th>Estado Civil</th>
                    <th>Data de Nascimento</th>
                    <th>Sexo</th>
                    <th>Endereço</th>
                    <th>Número</th>
                    <th>Complemento</th>
                    <th>Bairro</th>
                    <th>CEP</th>
                    <th>UF</th>
                    <th>Cidade</th>
                    <th>Telefone Residencial</th>
                    <th>Celular</th>                    
                    <th>Observações</th>
                    <th>Edições</th>
                </tr>                

                {% for funcionario in object_list %} 

                <tr>                        
                    <td>{{ funcionario.nome }}&nbsp; &nbsp;</td>
                    <td>{{ funcionario.cargo }}&nbsp;&nbsp;</td>
                    <td>{{ funcionario.cpf }}&nbsp;&nbsp;</td>
                    <td>{{ funcionario.rg }}&nbsp;&nbsp;</td>
                    <td>{{ funcionario.get_estado_civil_display }}&nbsp;&nbsp;</td>
                    <td>{{ funcionario.nascimento }}&nbsp;&nbsp;</td>
                    <td>{{ funcionario.get_sexo_display }}&nbsp;</td>
                    <td>{{ funcionario.endereco }}&nbsp;&nbsp;</td>
                    <td>{{ funcionario.numero }}&nbsp;&nbsp;</td>
                    <td>{{ funcionario.complemento }}&nbsp;&nbsp;</td>
                    <td>{{ funcionario.bairro }}&nbsp;&nbsp;</td>
                    <td>{{ funcionario.cep }}&nbsp;&nbsp;</td>
                    <td>{{ funcionario.get_uf_display }}&nbsp;&nbsp;</td>
                    <td>{{ funcionario.cidade }}&nbsp;&nbsp;</td>
                    <td>{{ funcionario.telefone_res }}&nbsp;&nbsp;</td>
                    <td>{{ funcionario.celular }}&nbsp;&nbsp;</td>                      
                    <td>&nbsp;{{ funcionario.observacoes }}&nbsp; &nbsp;</td>                            
                    <td>
                        <a href="{% url 'editar-funcionario' funcionario.pk %}" class="btn btn-warning btn-sm" title="Editar">
                            <i class="fa fa-pencil" aria-hidden="true"></i>
                        </a>                                             
                        <a href="{% url 'excluir-funcionario' funcionario.pk %}" class="btn btn-danger btn-sm" title="Excluir">
                            <i class="fa fa-trash" aria-hidden="true"></i>                           
                        </a>                        
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="18">Nenhum funcionario cadastrado.</td>
                </tr>
                {% endfor %}                
            </table>

            <ul class="pagination justify-content-center">
                
                {% if page_obj.has_previous %}
                    {% if request.GET.nome %}
                    <li class="page-item"><a class="page-link" href="?page=1&nome={{ request.GET.nome }}">&laquo; Primeira</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&nome={{ request.GET.nome }}">Anterior</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; Primeira</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
                    {% endif %}
                {% endif %}

                <li class="page-iterm">
                    <span class="page-link">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</span>
                </li>

                {% if page_obj.has_next %}
                    {% if request.GET.nome %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&nome={{ request.GET.nome }}">Próxima</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&nome={{ request.GET.nome }}">Última &raquo;</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a></li>
                    {% endif %}
                {% endif %}
            </ul>
            <hr>
        </div>
    {% endblock %}

cadastro/templates/cadastro/listas/paciente.html
{% extends 'paginas/modelo.html' %}
{% load static %}
{% load crispy_forms_tags %}

    {% block conteudo %}
    <div style="text-align: center;">
        <h3>{{ titulo }}</h3>
    </div>

    <hr>
    <form action="?" method="GET">
        <input type="text" name="paciente" id="" value="{{ request.GET.paciente }}" class="p-1 border" autocomplete="off" placeholder="Digite o nome do paciente">

        <button type="submit" class="btn btn-success">Buscar</button>

        <a href="{% url 'listar-pacientes' %}" class="btn btn-light">Limpar</a>
    </form>
    <hr>
    
    <a href="{% url 'cadastro-paciente' %}" class="btn btn-primary btn-sm">Adicionar Paciente</a>

    <hr>
        <div class="table-responsive">            
            <table class="table table-striped">              
                <tr>
                    <th>Paciente</th>
                    <th>Profissão</th>
                    <th>CPF</th>                    
                    <th>Estado Civil</th>
                    <th>Data de Nascimento</th>
                    <th>Sexo</th>
                    <th>Endereço</th>
                    <th>Número</th>
                    <th>Complemento</th>
                    <th>Bairro</th>
                    <th>CEP</th>
                    <th>UF</th>
                    <th>Cidade</th>
                    <th>Telefone Residencial</th>
                    <th>Celular</th>
                    <th>Número do cartão do SUS</th>
                    <th>Médico do Paciente</th>                    
                    <th>Observações</th>
                    <th>Edições</th>
                </tr>               

                {% for paciente in object_list %}

                <tr>
                    <td>{{ paciente.paciente }}&nbsp; &nbsp;</td>
                    <td>{{ paciente.profissao }}&nbsp;&nbsp;</td>
                    <td>{{ paciente.cpf }}&nbsp;&nbsp;</td>                    
                    <td>{{ paciente.get_estado_civil_display }}&nbsp;&nbsp;</td>
                    <td>{{ paciente.nascimento }}&nbsp;&nbsp;</td>
                    <td>{{ paciente.get_sexo_display }}&nbsp;</td>
                    <td>{{ paciente.endereco }}&nbsp;&nbsp;</td>
                    <td>{{ paciente.numero }}&nbsp;&nbsp;</td>
                    <td>{{ paciente.complemento }}&nbsp;&nbsp;</td>
                    <td>{{ paciente.bairro }}&nbsp;&nbsp;</td>
                    <td>{{ paciente.cep }}&nbsp;&nbsp;</td>
                    <td>{{ paciente.get_uf_display }}&nbsp;&nbsp;</td>
                    <td>{{ paciente.cidade }}&nbsp;&nbsp;</td>
                    <td>{{ paciente.telefone_res }}&nbsp;&nbsp;</td>
                    <td>{{ paciente.celular }}&nbsp;&nbsp;</td>
                    <td>{{ paciente.sus }}&nbsp;&nbsp;</td>
                    <td>{{ paciente.medico }}&nbsp;&nbsp;</td>                    
                    <td>&nbsp;{{ paciente.observacoes }}&nbsp; &nbsp;</td>
                    <td>
                        <a href="{% url 'editar-paciente' paciente.pk %}" class="btn btn-warning btn-sm" title="Editar">
                            <i class="fa fa-pencil" aria-hidden="true"></i>
                        </a>                        
                        <a href="{% url 'excluir-paciente' paciente.pk %}" class="btn btn-danger btn-sm" title="Excluir">
                            <i class="fa fa-trash" aria-hidden="true"></i>
                        </a>
                    </td>  
                </tr>
                {% empty %}
                <tr>
                    <td colspan="19">Nenhum paciente cadastrado.</td>
                </tr>
                {% endfor %}                     
            </table>
            
            <ul class="pagination justify-content-center">

                {% if page_obj.has_previous %}
                    {% if request.GET.paciente %}
                    <li class="page-item"><a class="page-link" href="?page=1&paciente={{ request.GET.paciente }}">&laquo; Primeira</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&paciente={{ request.GET.paciente }}">Anterior</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; Primeira</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
                    {% endif %}
                {% endif %}

                <li class="page-item">
                    <span class="page-link">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</span>
                </li>

                {% if page_obj.has_next %}
                    {% if request.GET.paciente %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&paciente={{ request.GET.paciente }}">Próxima</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&paciente={{ request.GET.paciente }}">Última &raquo;</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a></li>
                    {% endif %}
                {% endif %}
            </ul>
            <hr>
        </div>    
    {% endblock %}